name: "Windows Build"

on:
  push:
    branches: [ci/windows-build]
  workflow_dispatch:

jobs:
  build-x64:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      platform: "windows-latest"
      target: "x86_64-pc-windows-msvc"
      build-args: '-c {"bundle":{"createUpdaterArtifacts":false,"windows":{"signCommand":null}}}'
      upload-artifacts: true
      sign-binaries: false
    secrets: inherit

  build-arm64:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      platform: "windows-11-arm"
      target: "aarch64-pc-windows-msvc"
      build-args: '--target aarch64-pc-windows-msvc -c {"bundle":{"createUpdaterArtifacts":false,"windows":{"signCommand":null}}}'
      upload-artifacts: true
      sign-binaries: false
    secrets: inherit
