name: "Windows Build (x64)"

on:
  push:
    branches: [ci/windows-build]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      platform: "windows-latest"
      target: "x86_64-pc-windows-msvc"
      build-args: ""
      upload-artifacts: true
      sign-binaries: false
    secrets: inherit
